NomDualProyecto/4_Codigo/Version_001/SINOD/SINOD-web/src/main/java/com/mbn/sinod/web/mb/creaNomMB.java
package com.mbn.sinod.web.mb;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.mbn.sinod.model.dto.CabeceraDTO;
import com.mbn.sinod.model.entidades.Tsgnomcabecera;
import com.mbn.sinod.model.entidades.Tsgrhempleados;
import com.mbn.sinod.web.client.CabecerasWSClient;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import org.apache.deltaspike.core.api.scope.ViewAccessScoped;
import org.primefaces.context.RequestContext;

/**
 *
 * @author mipe
 */
//nombre de la clase en minuscula
@Named(value = "creaNomMB")
@ViewAccessScoped
public class creaNomMB implements Serializable {

    private Boolean boton;
    private Tsgrhempleados empleado;
    private List<Tsgnomcabecera> listaCabeceras;
    private Tsgnomcabecera CabeceraSelecionada;

    /**
     *
     */
    @PostConstruct
    public void iniciarVariables() {
        this.setEmpleado((Tsgrhempleados) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("empleado"));
        setListaCabeceras(CabecerasWSClient.listaCabecera());
    }

    /**
     *
     */
    public void dialogoCrear() {
        setBoton(true);
        setCabeceraSelecionada(new Tsgnomcabecera());
        RequestContext context = RequestContext.getCurrentInstance();
        context.execute("PF('dlgCrear').show();");
    }

    /**
     *
     * @throws JsonProcessingException
     */
    public void guardar() throws JsonProcessingException {
        System.out.println("entra a guardar");
        CabeceraDTO dtoRespuesta = new CabeceraDTO();
        dtoRespuesta.setCabecera(CabeceraSelecionada);
//        CabecerasWSClient.guardarConcepto(dtoRespuesta);
    }

    /**
     *
     */
    public void confirmarCrear() {
        setBoton(true);
        RequestContext context = RequestContext.getCurrentInstance();
        context.execute("PF('crearNom').show();");
    }

    /**
     * @return the boton
     */
    public Boolean getBoton() {
        return boton;
    }

    /**
     * @param boton the boton to set
     */
    public void setBoton(Boolean boton) {
        this.boton = boton;
    }

    /**
     *
     */
    public void mostrarCalcular() {
        setBoton(true);
        RequestContext context = RequestContext.getCurrentInstance();
        context.execute("PF('dlgCrear').show();");
    }

    /**
     * @return the listaCabeceras
     */
    public List<Tsgnomcabecera> getListaCabeceras() {
        return listaCabeceras;
    }

    /**
     * @param listaCabeceras the listaCabeceras to set
     */
    public void setListaCabeceras(List<Tsgnomcabecera> listaCabeceras) {
        this.listaCabeceras = listaCabeceras;
    }

    /**
     * @return the empleado
     */
    public Tsgrhempleados getEmpleado() {
        return empleado;
    }

    /**
     * @param empleado the empleado to set
     */
    public void setEmpleado(Tsgrhempleados empleado) {
        this.empleado = empleado;
    }

    /**
     * @return the CabeceraSelecionada
     */
    public Tsgnomcabecera getCabeceraSelecionada() {
        return CabeceraSelecionada;
    }

    /**
     * @param CabeceraSelecionada the CabeceraSelecionada to set
     */
    public void setCabeceraSelecionada(Tsgnomcabecera CabeceraSelecionada) {
        this.CabeceraSelecionada = CabeceraSelecionada;
    }
}

NomDualProyecto/4_Codigo/Version_001/SINOD/SINOD-web/src/main/webapp/Nomina/Calendario.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/template/template.xhtml"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">   

    <ui:define name="body">
        <main>
            <div class="container ">

                <!--Barra de navegación-->
                <div align="left">
                    <p:outputLabel value="#{messages['web.app.table.nomina.consultar.crear.calendario.menu']}"
                                   style="#{messages['web.app.style.menu']}" /> 
                </div>
                <center><h4>#{messages['web.app.table.nomina.consultar.crear.calendario.titulo']}</h4></center>
                <h:form id="Crear">
                    <p:growl id="mensaje" showDetail="true" sticky="true" />
                    <div class="#{messages['web.app.table.tabla']}" align="centered">
                        <p:dataTable id="datosQuincena" var="datosQuincena" 
                                     emptyMessage="#{messages['web.app.table.noData']}" 
                                     value="#{calendarioMB.listaQuincenas}" 
                                     widgetVar="datosNomCalTabla" 
                                     sortBy="#{datosQuincena.codQuincenaid}"
                                     sortOrder="DESCENDING"
                                     rows="#{messages['web.app.table.initialRows']}" paginator="true" 
                                     rowsPerPageTemplate="5,10,15" paginatorPosition="bottom" 
                                     style="font-size: small">
                            <f:facet name="header">
                                <!--boton agregar nomina-->
                                <p:commandButton icon="#{messages['web.app.icon.agregar']}" 
                                                 process="@this" 
                                                 action="#{calendarioMB.dialogoCrearConfig()}"
                                                 update="dlgCalen"
                                                 title="Agregar calendario nómina"
                                                 style="display:inline;
                                                 float:right;
                                                 font-size: small;
                                                 align-content: center;">
                                    <p:ajax update="CalendarioForm" resetValues="true" />
                                </p:commandButton>
                                <p:spacer height="27"/>
                            </f:facet>
                            <p:column headerText="Nombre" >
                                <h:outputText value="#{datosQuincena.desQuincena}" />
                            </p:column>
                            <p:column headerText="Periodo">
                                <h:outputText value="#{datosQuincena.codEjercicioidFk.cnuValorejercicio}" />
                            </p:column>
                            <p:column headerText="Fecha inicial">
                                <h:outputText value="#{datosQuincena.fecInicio}" >
                                    <f:convertDateTime pattern="#{messages['web.app.label.formatoFecha']}" />
                                </h:outputText>
                            </p:column>
                            <p:column headerText="Fecha final">
                                <h:outputText value="#{datosQuincena.fecFin}">
                                    <f:convertDateTime pattern="#{messages['web.app.label.formatoFecha']}" />
                                </h:outputText>
                            </p:column>
                            <p:column headerText="Fecha de pago">
                                <h:outputText value="#{datosQuincena.fecPago}">
                                    <f:convertDateTime pattern="#{messages['web.app.label.formatoFecha']}" />
                                </h:outputText>
                            </p:column>
                            <p:column headerText="Fecha de dispersión">
                                <h:outputText value="#{datosQuincena.fecDispersion}">
                                    <f:convertDateTime pattern="#{messages['web.app.label.formatoFecha']}" />
                                </h:outputText>                                
                            </p:column>
                            <!--                            <f:facet name="paginatorTopLeft">
                                                            <p:commandButton type="button" icon="pi pi-refresh" />
                                                        </f:facet>
                                                        <f:facet name="paginatorBottomRight">
                                                            <p:commandButton type="button" icon="pi pi-cloud-upload" />
                                                        </f:facet>-->
                        </p:dataTable>
                    </div>
                    <!--Datatable fin--> 
                </h:form>
                <!--inicio dialogo-->
                <p:dialog id="dlgCalen" resizable="false" closable ='false' 
                          styleClass="disable-scroll" draggable="false" 
                          widgetVar="dlgCalen" position="center center" 
                          header="#{messages['web.app.header.crearCalendarioNomina']}"
                          modal="true" height="4%" width="50%" style ="background: #FFFFFF;" >
                    <h:form id="CalendarioForm"> 
                        <h:outputText value="" />
                        <div class="#{messages['web.app.table.tabla']}"> 
                            <!--izq-->
                            <div class="ui-g-4 ui-md-4 ui-lg-4" style="padding: 0px; margin: 0px;">
                                <div class="row" style="padding-left: 5%;">
                                    <p:outputLabel value="#{messages['web.app.table.descripcion']}" title="Descripción de la quincena"/>
                                    <p:inputText maxlength="30" value="#{calendarioMB.calendarioSeleccionado.desQuincena}" 
                                                 required="true" requiredMessage="#{messages['web.app.required.calendario.descripcion']}">
                                        <p:ajax process="@this"/>
                                    </p:inputText>
                                </div>
                                <div class="row" style="padding-left: 5%;">
                                    <p:outputLabel value="#{messages['web.app.table.nomina.consultar.ejercicioF']}" 
                                                   style="color: black;" /> 
                                </div>
                                <div class="row" style="padding-left: 5%;">
                                    <p:selectOneMenu id="ejercicioF" value="#{calendarioMB.calendarioSeleccionado.codEjercicioidFk}" 
                                                     style="width: 90%;" 
                                                     converter="omnifaces.SelectItemsConverter" required="true" 
                                                     requiredMessage="#{messages['web.app.required.calendario.ejercicio']}">
                                        <f:selectItem itemLabel="Ejercicio fiscal" 
                                                      itemValue="#{null}"
                                                      noSelectionOption="true" />
                                        <f:selectItems value="#{calendarioMB.listaEjercicios}"  
                                                       var="ejercicioF" itemLabel="#{ejercicioF.cnuValorejercicio}" 
                                                       itemValue="#{null}" />
                                        <p:ajax event="change"  process="@this"/>
                                    </p:selectOneMenu>
                                </div>
                                <div class="row" style="padding-left: 5%;">
                                    <p:outputLabel value="#{messages['web.app.table.numQuin']}" />
                                    <p:inputText maxlength="2" value="#{calendarioMB.calendarioSeleccionado.cnuNumquincena}"
                                                 required="true" requiredMessage="#{messages['web.app.required.calendario.descripcion']}">
                                        <p:ajax process="@this"/>
                                    </p:inputText>
                                </div>

                            </div>
                            <div class="ui-g-2 ui-md-2 ui-lg-2"><!--nada--></div>
                            <div class="ui-g-4 ui-md-4 ui-lg-4" style="padding: 0px; margin: 0px;">
                                <!--der-->
                                <p:outputLabel for="inicial" value="#{messages['web.app.table.fechaInicio']}" />

                                <p:calendar id="inicial" value="#{calendarioMB.calendarioSeleccionado.fecInicio}" 
                                            inputStyleClass="dateTimeField" disabled="true"
                                            pattern="dd-MM-yyyy" mask="true" required="true" 
                                            requiredMessage="#{messages['web.app.required.calendario.fechainicio']}">
                                    <p:ajax event="dateSelect" />
                                </p:calendar>
                                <p:outputLabel for="final" value="#{messages['web.app.table.fechaFin']}" />
                                <p:calendar id="final" value="#{calendarioMB.calendarioSeleccionado.fecFin}" 
                                            inputStyleClass="dateTimeField" disabled="true"
                                            pattern="dd-MM-yyyy" mask="true" required="true" 
                                            requiredMessage="#{messages['web.app.required.calendario.fechafin']}">
                                    <p:ajax event="dateSelect" />
                                </p:calendar>
                                <p:outputLabel for="pago" value="#{messages['web.app.table.fechaPago']}" />
                                <p:calendar id="pago" value="#{calendarioMB.calendarioSeleccionado.fecPago}" 
                                            disabledWeekends="true"
                                            pattern="dd-MM-yyyy" mask="true" required="true" 
                                            requiredMessage="#{messages['web.app.required.calendario.fechapago']}">
                                    <p:ajax event="dateSelect" />
                                </p:calendar>
                                <p:outputLabel for="dispersion" value="#{messages['web.app.table.fechaDisp']}" />
                                <p:calendar id="dispersion" value="#{calendarioMB.calendarioSeleccionado.fecDispersion}" 
                                            disabledWeekends="true"
                                            pattern="dd-MM-yyyy" mask="true" 
                                            required="true" requiredMessage="#{messages['web.app.required.calendario.fechadispercion']}">
                                    <p:ajax event="dateSelect" />
                                </p:calendar>
                            </div>
                        </div>
                        <!-- Botones dialogo-->
                        <div align="right">
                            <!--visible, mostrar validar, deshabilitar calcular--> 
                            <!--PDF PF pag 117-->
                            <p:panel style="background: #FFFFFF; border: none;" id="botones">
                                <h:panelGroup id="Cancelar" >
                                    <p:commandButton 
                                        id="btnCancelarar"
                                        value="&nbsp; #{messages['web.app.button.cancelar']}"
                                        onclick="PF('dlgCalen').hide();"/>
                                </h:panelGroup>
                                <!--render hide-->
                                <h:panelGroup id="Guardar" >
                                    <p:commandButton id="btnGuardar"
                                                     value="&nbsp; #{messages['web.app.button.guardar']}"
                                                     update="CalendarioForm,Crear:mensaje,Crear:datosQuincena"
                                                     action="#{calendarioMB.guardarQuincena()}"
                                                     disabled="#{calendarioMB.disable}"
                                                     ajax="true" >
                                        <f:setPropertyActionListener value="#{calendarioMB.active}" target="#{calendarioMB.disable}"/>
                                    </p:commandButton>
                                </h:panelGroup>
                            </p:panel>
                        </div>
                        <!--</h:panelGrid>-->
                    </h:form>
                </p:dialog> 
                <!--Fin botones-->
                <!--fin dialogo-->
            </div>
        </main>
    </ui:define>
</ui:composition>

NomDualProyecto/4_Codigo/Version_001/SINOD/SINOD-web/src/main/webapp/Nomina/CrearT.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/template/template.xhtml"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">   

    <ui:define name="body">
        <main>
            <div class="container ">

                <!--Barra de navegación-->
                <div align="left">
                    <p:outputLabel value="#{messages['web.app.table.nomina.crear.menu']}"
                                   style="#{messages['web.app.style.menu']}" />    
                    <p:separator style="width: 100%; height:5px" />
                </div>

                <center><h4>Crear nómina</h4></center>
                <!-- Datatable FUNCIONA-->
                <h:form id="Crear">
                    <div class="#{messages['web.app.table.tabla']}" align="centered">
                        <p:dataTable id="datosNomTabla" var="datosNom" 
                                     emptyMessage="#{messages['web.app.table.noData']}" 
                                     value="#{creaNomMB.listaCabeceras}" 
                                     reflow="true" paginator="true"
                                     widgetVar="datosNomTab" 
                                     filteredValue="#{creaNomMB.listaCabeceras}" 
                                     rows="#{messages['web.app.table.initialRows']}"  
                                     paginatorPosition="bottom" 
                                     style="font-size: small"
                                     >
                            <f:facet name="header">
                                <!--Busqueda inicio-->

                                <!--                                <p:outputPanel>
                                                                    Resultados Consulta<br></br>
                                                                    <h:outputText value="Buscar:" />
                                                                    <p:inputText id="globalFilter" 
                                                                                 onkeyup="PF('crearNomTab').filter()" 
                                                                                 style="width:230px" 
                                                                                 placeholder="     Ingresa criterio de busqueda" 
                                                                                 />
                                                                </p:outputPanel>-->
                                <!--Busqueda inicio-->

                                <!--boton agregar nomina-->
                                <p:commandButton icon="#{messages['web.app.icon.agregar']}" 
                                                 process="@this" 
                                                 action="#{creaNomMB.dialogoCrear()}"
                                                 title="Agregar nómina"
                                                 style="display:inline;
                                                 float:right;
                                                 font-size: small;
                                                 align-content: center;"
                                                 update="dlgCrear"
                                                 >
                                </p:commandButton>
                                <p:spacer height="27"/>
                            </f:facet>

                            <p:column headerText="Nombre nómina">
                                <h:outputText value="#{datosNom.codNbnomina}" />
                            </p:column>

                            <p:column filterBy="#{datosNom.codQuincenaidFk.codEjercicioidFk.cnuValorejercicio}" 
                                      headerText="Ejercicio fiscal" 
                                      filterMatchMode="exact">
                                <f:facet name="filter">
                                    <p:selectOneMenu onchange="PF('crearNom.ejerFisc').filter()" 
                                                     styleClass="custom-filter">
                                        <f:selectItem itemLabel="Ejercicio fiscal" 
                                                      itemValue="#{null}" 
                                                      noSelectionOption="true" />
                                        <f:selectItems value="#{dtFilterView.ejerFisc}" />
                                    </p:selectOneMenu>
                                </f:facet>
                                <h:outputText value="#{datosNom.codQuincenaidFk.codEjercicioidFk.cnuValorejercicio}" />
                            </p:column>

                            <p:column filterBy="#{datosNom.codQuincenaidFk.cnuNumquincena}" 
                                      headerText="Quincena" 
                                      filterMatchMode="exact">
                                <f:facet name="filter">
                                    <p:selectOneMenu onchange="PF('crearNom.quin').filter()" 
                                                     styleClass="custom-filter">
                                        <f:selectItem itemLabel="Quincena" itemValue="#{null}" 
                                                      noSelectionOption="true" />
                                        <f:selectItems value="#{dtFilterView.quin}" />
                                    </p:selectOneMenu>
                                </f:facet>
                                <h:outputText value="#{datosNom.codQuincenaidFk.cnuNumquincena}" />
                            </p:column>

                            <p:column filterBy="#{crearNom.tipoNom}" 
                                      headerText="Tipo nómina" 
                                      filterMatchMode="exact"> 
                                <f:facet name="filter">
                                    <p:selectOneMenu onchange="PF('crearNom.quin').filter()" 
                                                     styleClass="custom-filter">
                                        <f:selectItem itemLabel="Tipo nómina" 
                                                      itemValue="#{null}" 
                                                      noSelectionOption="true" />
                                        <f:selectItems value="#{dtFilterView.tipoNom}" />
                                    </p:selectOneMenu>
                                </f:facet>
                                <h:outputText value="#{datosNom.codTiponominaidFk.codNomina}" />
                            </p:column>

                            <f:facet name="paginatorTopLeft">
                                <p:commandButton type="button" icon="pi pi-refresh" />
                            </f:facet>

                            <f:facet name="paginatorBottomRight">
                                <p:commandButton type="button" icon="pi pi-cloud-upload" />
                            </f:facet>

                        </p:dataTable>

                    </div>
                    <!--Datatable fin--> 
                </h:form>

                <p:confirmDialog id="crearNom" widgetVar="crearNom" 
                                 header="Eliminar" closable="false"
                                 message="¿Desea eliminar  el argumento?" 
                                 showEffect="fade" hideEffect="fade" >
                    <center>
                        <p:growl id="mensaje" showDetail="true" />
                        <p:commandButton value="#{messages['web.app.button.no']}" 
                                         process="@this" 
                                         onclick="PF('crearNom').hide();" />
                        <p:commandButton value="#{messages['web.app.button.si']}" process="@this" 
                                         onclick="PF('crearNom').hide();" />
                    </center>
                </p:confirmDialog>

                <!--Dialogos inicio-->
                <p:dialog id="dlgCrear" 
                          resizable="false" 
                          closable ='false' 
                          styleClass="disable-scroll" 
                          draggable="false" 
                          header="Crear nómina" 
                          widgetVar="dlgCrear" 
                          position="center center" 
                          modal="true" 
                          height="4%" 
                          width="50%" 
                          style ="background: #FFFFFF;" >

                    <h:form id="FormCrear">
                        <p:panel class="#{messages['web.app.table.tabla']}" 
                                 style="background: #FFFFFF; border: none;" id="detallePane1s">
                            <p:growl id="growl1" showDetail="true" sticky="false" /> 
                            <div class="ui-g-5 ui-md-4 ui-lg-5" >
                                <div class="row" align="center">
                                    <p:outputLabel value="Nombre de la nómina: " />
                                    <p:inputText id="ClaveDO" maxlength="20" size="20" value="#{creaNomMB.cabeceraSelecionada.codNbnomina}"
                                                 class="materialize-textarea" required="true">
                                        <p:ajax process="@this" />
                                    </p:inputText>
                                </div>
                                <div class="row" align="center">
                                    <p:outputLabel for="ejerFis" value="Ejercicio fiscal:" />
                                    <br></br> <br></br>

                                    <p:selectOneMenu id="ejerFis" 
                                                     value="#{selectOneMenuView.console}" 
                                                     style="width:90%">
                                        <f:selectItem itemLabel="Ejercicio fiscal" itemValue="Ejercicio fiscal" />
                                        <f:selectItem itemLabel="2017" itemValue="2017" />
                                        <f:selectItem itemLabel="2018" itemValue="2018" />
                                        <f:selectItem itemLabel="2019" itemValue="2019" />
                                    </p:selectOneMenu>
                                </div>
                            </div>

                            <div class="ui-g-1 ui-md-1 ui-lg-1" >
                            </div>

                            <div class="ui-g-5 ui-md-4 ui-lg-5" >
                                <div>
                                    <p:outputLabel for="inicioQuin1" value="Inicio quincena:" />
                                    <p:calendar id="inicioQuin1" value="#{calendarView.date}" mindate="1/7/19" maxdate="15/8/19" />
                                    <p:outputLabel for="finQuin1" value="Fin quincena:" />
                                    <p:calendar id="finQuin1" value="#{calendarView.date}" mindate="1/8/19" maxdate="15/8/19" />
                                </div>
                            </div>
                        </p:panel>

                        <div style="padding-left: 60%">
                            <p:commandButton value="#{messages['web.app.button.cancelar']}" 
                                             onclick="PF('dlgCrear').hide();" 
                                             id="btnCancelar" 
                                             style="margin-right:2%;" 
                                             styleClass="ui-priority-primary" />
                            <p:commandButton value="#{messages['web.app.button.crear']}"
                                             action="#{creaNomMB.guardar()}"
                                             process="@this"
                                             id="btnCrear" 
                                             style="margin-right:2%;" 
                                             styleClass="ui-priority-primary"
                                             update="crearNom"/>
                        </div>
                    </h:form>
                </p:dialog>
                <!--Dialogos fin-->

            </div> <!-- end container -->
        </main>

    </ui:define>
</ui:composition>